title: REGISM – Shedding Light on Task Decomposition in Program Synthesis
description: Investigating the role of task decomposition in program synthesis.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
